# Generated by Django 5.1.6 on 2026-08-20 05:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=60)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "grams"),
                            ("ml", "milliliters"),
                            ("item", "items"),
                            ("tbsp", "tablespoons"),
                        ],
                        default="g",
                        max_length=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Estimated price per canonical unit.",
                        max_digits=8,
                    ),
                ),
                ("contains_gluten", models.BooleanField(default=False)),
                ("contains_dairy", models.BooleanField(default=False)),
                ("contains_nuts", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="recipe",
            name="calories_per_serving",
            field=models.PositiveSmallIntegerField(default=500),
        ),
        migrations.AddField(
            model_name="recipe",
            name="carbs_grams",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("40.0"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="fat_grams",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("15.0"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_dairy_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_gluten_free",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_nut_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_vegan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_vegetarian",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="prep_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="recipe",
            name="protein_grams",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("20.0"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.PositiveSmallIntegerField(
                default=4, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.TextField(
                blank=True, help_text="Human-readable ingredient list"
            ),
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantity for the full recipe in the ingredient's canonical unit.",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=120)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_lines",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_lines",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="normalized_ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
            ),
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekly_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("70.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                (
                    "meals_per_week",
                    models.PositiveSmallIntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "meal_calorie_target",
                    models.PositiveSmallIntegerField(
                        default=600,
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(2000),
                        ],
                    ),
                ),
                (
                    "meal_protein_target",
                    models.PositiveSmallIntegerField(
                        default=25,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                ("vegetarian", models.BooleanField(default=False)),
                ("vegan", models.BooleanField(default=False)),
                ("gluten_allergy", models.BooleanField(default=False)),
                ("dairy_allergy", models.BooleanField(default=False)),
                ("nut_allergy", models.BooleanField(default=False)),
                (
                    "excluded_ingredients",
                    models.ManyToManyField(
                        blank=True, related_name="excluded_by", to="recipes.ingredient"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyMealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("budget_limit", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("average_pantry_overlap", models.PositiveSmallIntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("solver_summary", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-week_start", "-generated_at"),
            },
        ),
        migrations.CreateModel(
            name="PlannedMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_index",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(6)]
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[("lunch", "Lunch"), ("dinner", "Dinner")],
                        default="dinner",
                        max_length=10,
                    ),
                ),
                ("estimated_cost", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pantry_overlap", models.PositiveSmallIntegerField(default=0)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_meals",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="recipes.weeklymealplan",
                    ),
                ),
            ],
            options={
                "ordering": ("day_index", "slot"),
            },
        ),
        migrations.CreateModel(
            name="PantryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pantry_items",
                        to="recipes.ingredient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pantry_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("ingredient__name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "ingredient"), name="unique_user_pantry_item"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklymealplan",
            constraint=models.UniqueConstraint(
                fields=("user", "week_start"), name="unique_user_plan_week"
            ),
        ),
        migrations.AddConstraint(
            model_name="plannedmeal",
            constraint=models.UniqueConstraint(
                fields=("plan", "day_index", "slot"), name="unique_plan_day_slot"
            ),
        ),
    ]
